xrdb $XDG_CONFIG_HOME/x11/xresources
picom -b 
~/.fehbg
redshift -l 40:-77 &
xss-lock --transfer-sleep-lock autolock &
mpd
start-statusbar &
dunst &
setxkbmap -option caps:escape

xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

setxkbmap -option grp:alt_shift_toggle us,gr

exec dwm
