. $HOME/.profile
xrdb $HOME/.config/x11/xresources
nohup picom -b &
#~/.fehbg
#redshift -l 40:-77 &
#xss-lock --transfer-sleep-lock autolock &
mpd &
$HOME/.local/bin/start-statusbar
dunst &
setxkbmap -option caps:escape

xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

exec dwm
