. $HOME/.profile
xrdb $HOME/.config/x11/xresources
nohup picom -b &
#~/.fehbg
#redshift -l 40:-77 &
xidle -program $HOME/.local/bin/lock -timeout 600 &
mpd &
$HOME/.local/bin/start-statusbar
dunst &
setxkbmap -option caps:escape

xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation" 1
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Button" 2
xinput set-prop "/dev/wsmouse" "WS Pointer Wheel Emulation Axes" 6 7 4 5

if [ -x ${PREFIX}/bin/dbus-launch -a -z "${DBUS_SESSION_BUS_ADDRESS}" ]; then
	eval `dbus-launch --sh-syntax --exit-with-x11`
fi

ulimit -Sc 0
xset -b off

exec dwm
