#!/usr/local/bin/ksh
function groot {
    root_dir="$(git rev-parse --show-toplevel 2> /dev/null)"

    if [[ ! -z $root_dir ]]; then
        cd $root_dir
    else
        print "ERROR: Not within a git repository"
    fi
}
