require "douglas.options"
require "douglas.keys"
require "douglas.plugins"
require "douglas.colorscheme"
require "douglas.completions"
require "douglas.lsp"
require "douglas.telescope"
require "douglas.treesitter"
require "douglas.lualine"
require "douglas.gitsigns"
require "douglas.autopairs"
require "douglas.pandoc"
require "douglas.comment"
require "douglas.latex"


